[package]
name = "spoti_afk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspotify = "0.11.5"
dotenv = "0.15.0"
open = "2.1.2"
urlshortener = "3.0.0"
futures = "0.3.21"
